# Site settings
title: The Oxford University Invariant Society
email: invariants@invariants.org.uk
description: > # this means to ignore newlines until "baseurl:"
  We are the Oxford University student society for Mathematics. Our goals are to
  promote Mathematics and to provide a social environment for students of Mathematics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://invariants.org.uk/" # the base hostname & protocol for your site
facebook_page: oxford.invariants
copyright: Copyright &copy; The Oxford Invariants Society 2017

# Build settings
future: true
markdown: kramdown
exclude:
  - README.md
  - RELEASENOTES.md
  - Makefile
  - app

# Serve settings
detach: true

# Global settings
safe: true
timezone: Europe/London
defaults:
  - scope:
      path: ""
      type: events
    values:
      layout: event
      time: 8:15pm
      day: Tuesday
      location: L2

# Custom collections
collections:
  # society event
  events:
    output: true
